/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_battery_service                19
#define gattdb_battery_level                  21
#define gattdb_sensor                         22
#define gattdb_temperature                    24
#define gattdb_humidity                       26
#define gattdb_aggregate                      28
#define gattdb_current_time                   30
#define gattdb_timestamp                      32
#define gattdb_communication                  33
#define gattdb_spp                            35


#endif // __GATT_DB_H
