/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_battery_service                19
#define gattdb_battery_level                  21
#define gattdb_characteristic_presentation_format 22
#define gattdb_sensor                         23
#define gattdb_temperature                    25
#define gattdb_humidity                       27
#define gattdb_aggregate                      29
#define gattdb_current_time                   31
#define gattdb_timestamp                      33
#define gattdb_communication                  34
#define gattdb_spp                            36


#endif // __GATT_DB_H
